#!/usr/bin/bash

# run python script to add wget to all necessary lines
python data_download.py $1

# make the shell script generated by the python script executable
chmod +x data_downloader.sh

# run the data downloader
./data_downloader.sh

# remove data_downloader.sh after use
rm data_downloader.sh
